[workspace]
resolver = "3"
members = [
    "crates/boxsh-core",
    "crates/boxsh-fs",
    "crates/boxsh-commands",
    "crates/boxsh-shell",
    "crates/boxsh-utils",
    "crates/boxsh-abi",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nishantjoshi/boxsh"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
