[package]
name = "boxsh-abi"
description = "WebAssembly loading support for boxsh."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
boxsh-core = { path = "../boxsh-core" }
boxsh-utils = { path = "../boxsh-utils" }
