[package]
name = "nobox-abi"
description = "WebAssembly loading support for nobox."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nobox-core = { path = "../nobox-core" }
nobox-utils = { path = "../nobox-utils" }
